### PR TITLE
Add tests for freestyle dynamic

### PR DESCRIPTION
**Pull request by danwenzel**
Adds acceptance tests and a property assertion/test for freestyle dynamic

### CODE REVIEW

**Comment by danwenzel** [comment]
Good thoughts, @lukemelia .  I was following the pattern of the existing acceptance tests, so perhaps @chrislopresto has some thoughts.  If we're going to make a change, it's probably better to do it throughout the test suite to keep things consistent .

**Comment by chrislopresto** [comment]
Awesome. Thanks, @danwenzel!

@lukemelia It may indeed be nice to refactor the entire test suite away from page objects. I'd be happy to merge this PR as is to gain the test coverage in the meantime, though. Thoughts?

**Comment by danwenzel** [comment]
@lukemelia - What do you think?  Ok to merge this, and then separately refactor tests later?

**Comment by lukemelia** [comment]
Whoops, sorry. I'm +1. Don't let the perfect be the enemy of the good!

**Comment by chrislopresto** [comment]
Thanks @danwenzel!

**Pull request merged**
