### PR TITLE
Remove jQuery dependency

### PR DESCRIPTION
**Pull request by scanieso**
Addresses #148 

## What's in this PR?
This PR removes jQuery by replacing DOM selection, script injection, jQuery events, and test helpers.

## Dependency changes
Important to note that this does use an [alpha version of ember-cli-page-object](https://github.com/san650/ember-cli-page-object/releases/tag/v1.13.0-alpha.1) to be able to disable its jQuery dependency.
- Removed ember-ajax
- Added ember-native-dom-event-dispatcher
- Added ember-native-dom-helpers
- Upgraded ember-cli-page-object to 1.13.0-alpha.1

### CODE REVIEW

**Comment by scanieso** [comment]
Investigating failing build 😱 🙈

**Comment by ro0gr** [comment]
2.8 and 2.12 builds are failing.
This is exactly that is said in the article you posted in issue:
>At the time of this writing, you need Ember.js >= 2.13.0-beta.2

**Comment by simonihmig** [comment]
Yes, I think for those versions jQuery needs to be included, and `ember-native-dom-event-dispatcher` excluded. This is what I'm doing here:
* https://github.com/kaliber5/ember-bootstrap/blob/master/config/ember-try.js#L104
* https://github.com/kaliber5/ember-bootstrap/blob/master/ember-cli-build.js#L14-L16

**Comment by scanieso** [comment]
Thanks all! Fixed :)

**Comment by chrislopresto** [comment]
Nice.. thanks!

**Pull request merged**
