### PR TITLE
Don't include blank lines when determining how much to unindent

### PR DESCRIPTION
**Pull request by danwenzel**
Fixes https://github.com/chrislopresto/ember-freestyle/issues/173

### CODE REVIEW

**Comment by thomblake** [comment]
Nice! I like the solution of not using a regex to get around the problem of stripping the blank lines and leaving extra spaces.

**Comment by danwenzel** [comment]
@chrislopresto @lukemelia - Any ideas as to what's going on with Travis?  I'm not sure how those `sudo` commands would have ever worked with `sudo: false` being set in travis.yml.

**Comment by danwenzel** [comment]
Thanks, @chrislopresto!  Ok to merge this then?

**Comment by danwenzel** [comment]
Hey @chrislopresto .  Trying again:  You ok with merging this?

**Comment by lukemelia** [comment]
Nice work @danwenzel!

**Pull request merged**
