### PR TITLE
Support for nested addon

### PR DESCRIPTION
**Pull request by skwongr**

### CODE REVIEW

**Comment by lukemelia** [comment]
Can you say more about the use case for this @skwongr? In my experience so far, I've only wanted to use freestyle only as a devDependency in addons.

**Comment by skwongr** [comment]
This was a fix for using this addon within another addon or ember-engines in my case.

**Comment by lukemelia** [comment]
Merged manually

**Comment by lukemelia** [comment]
Thanks and apologies for the long delay!

**Pull request closed without merging**
