### PR TITLE
Documentation and rendering improvements to freestyle-dynamic

### PR DESCRIPTION
**Pull request by lukemelia**
- Add documentation on freestyle-dynamic
- Extract title component (freestyle-filterable-title) to avoid redundancy
- Move title to above dynamic property controls when using freestyle-dynamic
- Render dynamic property controls using a styled fieldset for nicer UX
- Make focus filter apply to dynamic controls as well as the usage

### CODE REVIEW

**Comment by lukemelia** [comment]
## Before:

image

## After:

image

## Docs:

image

**Comment by lukemelia** [comment]
Once we get this merged, I have a branch ready to go that builds on it to add `freestyle-dynamic-collection`, which lets you wrap a freestyle-collection with a live control panel.

**Comment by lolmaus** [comment]
This PR went stale?

Documentation for dynamic properties is still missing. Let's get this merged! 🙏

**Comment by lukemelia** [comment]
This feature seems likely to be supplanted by the new Freestyle::Usage API being added in https://github.com/chrislopresto/ember-freestyle/pull/457

**Pull request closed without merging**
