### PR TITLE
feat: Add support for markdown tables

### PR DESCRIPTION
**Pull request by NoahFisher**
#195 - related issue.

### CODE REVIEW

**Comment by NoahFisher** [comment]
This change is going to require some styling for tables as it looks like the screenshot below at the moment. I'm happy to add this, but wanted to gauge interest before investing time in it. My strategy was to make the tables look like github markdown tables. Any feedback before starting down this path would be appreciated! 

Screen Shot 2019-05-10 at 8 41 32 AM

**Comment by NoahFisher** [comment]
Updated to add styling for tables:
Screen Shot 2019-05-10 at 9 12 15 AM

**Comment by NoahFisher** [comment]
@chrislopresto chasing on this.

**Comment by NoahFisher** [comment]
@chriskrycho @chrislopresto Is there anything I can do to get this moving forward?

**Comment by NoahFisher** [comment]
@chriskrycho @chrislopresto chasing on this again.

**Comment by chriskrycho** [comment]
I’m not the guy to ask; I fixed a Sass build issue once but am otherwise not engaged with this particular effort! 😄

**Comment by NoahFisher** [comment]
@chriskrycho got it. Apologies for the noise (tagged the wrong Chris 😆)

**Comment by chrislopresto** [comment]
Thanks!

**Pull request merged**
