### PR TITLE
BREAKING CHANGE: Switch to AST transform for freestyle-usage source preview, drop support for comment-delineated snippets, remove freestyle-notes component

### PR DESCRIPTION
**Pull request by chrislopresto**
This PR greatly simplifies the mechanism we use to provide source code previews in your Freestyle guide. 

* Drops lesser-used functionality related to comment-delineated snippets, 
* Drops the freestyle-notes component along with its markdown support

We have provided documentation for techniques to replace the removed features. In short:

* Use [ember-code-snippet](https://github.com/ef4/ember-code-snippet) for embedding comment-delineated snippets
* Use freestyle-annotation to associate documentation with a freestyle-usage instance
* Create your own MarkdownComponent that uses [remarkable](https://github.com/jonschlinkert/remarkable) to render markdown documentation

**To do before merging**

- [x] Solution to preserve whitespace formatting of freestyle-usage source
- [x] Editorial pass on README
- [x] Editorial pass on documentation page
- [x] Clean up global styles in dummy app now that we removed bulma
- [x] Update ember-try matrix to drop 3.8
- [x] Verify in real-world apps

**Visual proof of everything still working**

image

### CODE REVIEW

**Comment by pichfl** [comment]
Not judge, but shouldn't a breaking change also result in a major release? I guess anything before 1.0.0 is weird country anyway, just wanted to ask.

**Comment by lukemelia** [comment]
@pichfl Hi Florian, great question! This project endeavors to follow Semantic Versioning and per the SemVer spec, "Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable." We recognize that people are using this addon in production as it has been out for a long time. As a result, we have been careful to include helpful error messages and upgrade guidance in this release. That said, we're not happy with the API yet and plan to move to an API like what is sketched in #340 before making this addon 1.0. If you have any questions, or upgrade trouble that you don't see clear answers to, let us know.

**Comment by pichfl** [comment]
I like where it is going 🙂

**Comment by Turbo87** [comment]
FWIW the behavior of `^` version constraints in `package.json` is:

- below v1.0.0 it only updates to the latest patch version
- above v1.0.0 it updates to the latest minor version

**Pull request merged**
