### PR TITLE
Update ember-cli-sass to use Dart Sass.

### PR DESCRIPTION
**Pull request by chriskrycho**
NOTE: this is a placeholder commit that will be revised! It will be amended when aexmachina/ember-cli-sass#205 is merged and a release is cut with that change in place.

I'm opening this PR to allow my team to make progress via the fork in the meantime.

### CODE REVIEW

**Comment by chrislopresto** [comment]
@chriskrycho Thanks so much for sorting this out!

**Comment by chriskrycho** [comment]
@chrislopresto this is now ready to go!

**Comment by chriskrycho** [comment]
@chrislopresto not sure what's up with this lint rule failure; I didn't change anything but the dependencies here.

**Comment by ro0gr** [comment]
@chriskrycho seems to be the same issue I've faced here https://github.com/chrislopresto/ember-freestyle/pull/184#issuecomment-443916028

you can check the fix in the last commit https://github.com/chrislopresto/ember-freestyle/pull/184/commits/3fa6852b18f5baa9cf6bed06ba1c4ef0909488ee

**Comment by chrislopresto** [comment]
Ah, right. I forgot #184 was lingering and had that issue. Thanks for troubleshooting and chiming in, @ro0gr.

#184 looks good, though I need to wrap my head around it a bit or ask @lukemelia or @danwenzel to chime in.

@chriskrycho Do you want to cherry-pick that fix in so we can merge this PR in the meantime?

**Comment by chriskrycho** [comment]
Can do! Will push it up shortly!

**Comment by chriskrycho** [comment]
And done! @chrislopresto this should be ready for merge (pending CI being green)!

**Pull request merged**
