### PR TITLE
generate blueprint in dummy app for addons

### PR DESCRIPTION
**Pull request by mszoernyi**
I started to use this for one of our addons which contains our components. This PR changes the path for the blueprints while installed in an addon.

I would like to add tests for this but till trying to figure out how to do this. And fix these ones as well

* ember-freestyle needs to be a dependency, not a devDependency
* Tell the build where to search for snippets
  * In ember-cli-build.js:
```
var app = new EmberAddon(defaults, {
 // ...
 snippetSearchPaths: ['tests/dummy/app', 'app/styles']
});
```

What's the reason for the `dependency` requirement?

Would it make sense to handle the `snippetSeachPath` setting [here](https://github.com/chrislopresto/ember-freestyle/blob/master/index.js#L44-L49)?

**Todo's**

- [x] Generate blueprints in dummy app for addons

Moved into own issues
- set default `snippetSearchPath` for addons and apps (https://github.com/chrislopresto/ember-freestyle/issues/30)
- make app.scss overridable (related https://github.com/chrislopresto/ember-freestyle/issues/20)

### CODE REVIEW

**Comment by chrislopresto** [comment]
@mszoernyi There should be no need to install as a `dependency`... a `devDependency` should work just fine.

**Comment by mszoernyi** [comment]
@chrislopresto it is mentioned in the working with addons chapter https://github.com/chrislopresto/ember-freestyle/blob/master/README.md#working-within-an-addon

It was quite confusing when I started using this addon so I thought it should be more clear?!?

**Comment by chrislopresto** [comment]
@mszoernyi I would like to merge this in as is. We could worry about snippet search paths and scss in separate issues/PRs.

Would you mind rebasing? I made changes to the README, so there are conflicts now.

**Comment by mszoernyi** [comment]
Will do tonight or tomorrow morning

**Comment by mszoernyi** [comment]
Done. I removed the last line of the working with addon block because this PR actually fixes it.

**Comment by chrislopresto** [comment]
Thanks, @mszoernyi!

**Pull request merged**
