### PR TITLE
Feature plain css

### PR DESCRIPTION
**Pull request by PoslinskiNet**
It should resolve issue reported here:

https://github.com/chrislopresto/ember-freestyle/issues/143

### CODE REVIEW

**Comment by PoslinskiNet** [comment]
@chrislopresto can wait for your feedback :).

**Comment by PoslinskiNet** [comment]
@andrewmcc any idea when we can merge this :) ?

**Comment by lukemelia** [comment]
I'm a fan of not requiring an app to use sass, but not a fan of having to remember to commit generated code to the repo. Some other options:

1) Switch to authoring in css (cons: annoying not to have sass features available)
2) Make ember-cli-sass a dev dependency only and generate css during compilation (cons: consumers still need to deal with node-sass dep in development)

**Comment by PoslinskiNet** [comment]
So what do you suggest to make this change possible? I'm very open to solutions that will result in getting rid `node-sass` dependency at all. As you can see, I've left node-sass rebuilt for easier maintainability of the package.

**Comment by PoslinskiNet** [comment]
Any thoughts on my previous comment @lukemelia 😈  ?

**Comment by lukemelia** [comment]
@PoslinskiNet The two solutions I offered could both work from my perspective.

**Comment by caselas** [comment]
@PoslinskiNet any interest in picking this back up? Let me know if I can help. 🤙

**Comment by PoslinskiNet** [comment]
@caselas I don't have free manpower at the moment so If you like to move on with the first option that @lukemelia suggested it would be epic. The case where `node-sass` is required in the add-on is no-go for me, when I'm using `node-sass` in our app with a different configuration.

**Comment by bertdeblock** [comment]
Is this PR still relevant?

**Pull request closed without merging**
