### PR TITLE
WIP - Yielded Component API

### PR DESCRIPTION
**Pull request by knownasilya**
⚠️ This is a WIP, don't merge yet

### CODE REVIEW

**Comment by chrislopresto** [comment]
We should use this opportunity to create an acceptance test that fails on versions of Ember prior to 2.3. We should then pull in https://github.com/cibernox/ember-hash-helper-polyfill to go green.

**Comment by knownasilya** [comment]
The hash helper polyfill will not allow calling components from it, e.g. `{{fs.subsection}}`. The helper only allows you to structure the output correctly, but Ember has other code that allows invoking components in this way.

**Comment by mszoernyi** [comment]
I like this idea. Whats the final goal? To have all freestyle components have this API or just for the subsection?

**Comment by knownasilya** [comment]
@mszoernyi I think only where it makes sense. There will be more areas, and we plan to expose some of the frequent components, like `usage` as well.

**Comment by simonihmig** [comment]
What's the status on this? Would love to get this in!

Would also make sense for the `collection`/`variant` components.

**Comment by chrislopresto** [comment]
@simonihmig @knownasilya With the 0.4.0 release, we are now officially supporting Ember 2.8+. So that clears the way to clean up the various section / subsection implementations with no need to polyfill.

Are either of you interested in picking up work on this branch? It would be great remove the need for so much boilerplate!

**Comment by knownasilya** [comment]
@chrislopresto which components should yield? I'd love to hear your thoughts on this.

**Pull request closed without merging**
